--[[
    StartupConfig utility for managing startup.lua generation.

    The startup.config file stores user preferences:
    - package: The package to run on startup
    - parameters: Optional arguments to pass
    - version: Config schema version for future migrations

    When mpm self_update runs, it regenerates startup.lua from this config,
    ensuring the startup script stays current with MPM updates.
]]
local StartupConfig = nil

local CONFIG_PATH = "/startup.config"
local STARTUP_PATH = "/startup.lua"
local CONFIG_VERSION = 1

StartupConfig = {
    --- Get the current startup configuration
    --- @return table|nil config
    getConfig = function()
        local File = exports("Utils.File")
        local content = File.get(CONFIG_PATH)

        if not content then
            return nil
        end

        local config = textutils.unserialiseJSON(content)
        return config
    end,

    --- Save startup configuration
    --- @param package string Package name
    --- @param parameters string Optional parameters
    --- @return boolean success
    saveConfig = function(package, parameters)
        local File = exports("Utils.File")
        local Validation = exports("Utils.Validation")

        if Validation.isEmpty(package) then
            return false
        end

        local config = {
            version = CONFIG_VERSION,
            package = package,
            parameters = parameters or "",
            updatedAt = os.date and os.date("%Y-%m-%d %H:%M:%S") or "unknown"
        }

        return File.put(CONFIG_PATH, textutils.serializeJSON(config))
    end,

    --- Remove startup configuration
    --- @return boolean success
    removeConfig = function()
        local File = exports("Utils.File")

        if File.exists(CONFIG_PATH) then
            return File.delete(CONFIG_PATH)
        end

        return true
    end,

    --- Check if startup is configured
    --- @return boolean configured
    isConfigured = function()
        local File = exports("Utils.File")
        return File.exists(CONFIG_PATH)
    end,

    --- Generate startup.lua content from config
    --- @param config table Startup configuration
    --- @return string content
    generateStartupScript = function(config)
        if not config or not config.package then
            return nil
        end

        local script = [[-- MPM Startup Script
-- Auto-generated by MPM. Edit startup.config to change settings.
-- Regenerate with: mpm startup --refresh

-- Update MPM itself first
shell.run('mpm self_update')

-- Update installed packages
shell.run('mpm update')

-- Run the configured package
shell.run('mpm run ]] .. config.package

        if config.parameters and config.parameters ~= "" then
            script = script .. " " .. config.parameters
        end

        script = script .. "')\n"

        return script
    end,

    --- Write startup.lua from current config
    --- @return boolean success, string|nil error
    regenerateStartup = function()
        local File = exports("Utils.File")

        local config = StartupConfig.getConfig()
        if not config then
            return false, "No startup configuration found"
        end

        local content = StartupConfig.generateStartupScript(config)
        if not content then
            return false, "Failed to generate startup script"
        end

        local success = File.put(STARTUP_PATH, content)
        if not success then
            return false, "Failed to write startup.lua"
        end

        return true, nil
    end,

    --- Configure startup and generate startup.lua
    --- @param package string Package name
    --- @param parameters string Optional parameters
    --- @return boolean success
    configure = function(package, parameters)
        -- Save config
        local saved = StartupConfig.saveConfig(package, parameters)
        if not saved then
            return false
        end

        -- Generate startup.lua
        local success, err = StartupConfig.regenerateStartup()
        return success
    end,

    --- Clear startup configuration and optionally remove startup.lua
    --- @param removeStartup boolean Whether to also delete startup.lua
    --- @return boolean success
    clear = function(removeStartup)
        local File = exports("Utils.File")

        StartupConfig.removeConfig()

        if removeStartup and File.exists(STARTUP_PATH) then
            File.delete(STARTUP_PATH)
        end

        return true
    end
}

return StartupConfig
