--[[
    Startup command: mpm startup [package]

    Configures a package to run on computer startup.
    If no package specified, shows interactive prompt.
]]
local startupModule = nil

startupModule = {
    usage = "mpm startup [package] [args...]",

    run = function(package, ...)
        local Validation = exports("Utils.Validation")
        local File = exports("Utils.File")
        local PackageDisk = exports("Utils.PackageDisk")

        local args = {...}
        local parameters = ""

        -- Interactive mode if no package specified
        if Validation.isEmpty(package) then
            print("Enter the package name for startup script:")
            package = read()

            if Validation.isEmpty(package) then
                print("Error: Package name cannot be empty.")
                return
            end

            print("Enter optional parameters (or leave blank):")
            parameters = read() or ""
        else
            -- Build parameters from remaining args
            if #args > 0 then
                parameters = table.concat(args, " ")
            end
        end

        -- Validate package exists
        if not PackageDisk.isInstalled(package) then
            print("Warning: Package '" .. package .. "' is not currently installed.")
            print("The startup script will attempt to run it anyway.")
            print("")
            print("Continue? (y/n)")
            local confirm = read()
            if confirm:lower() ~= "y" then
                print("Cancelled.")
                return
            end
        end

        -- Build startup script
        local startup_content = [[-- MPM Startup Script
-- Generated by: mpm startup

-- Update packages before running
shell.run('mpm update')

-- Run the configured package
shell.run('mpm run ]] .. package

        if parameters ~= "" then
            startup_content = startup_content .. " " .. parameters
        end

        startup_content = startup_content .. [[')\n]]

        -- Write startup script
        local success = File.put("/startup.lua", startup_content)

        if success then
            print("")
            print("Startup script configured!")
            print("  Package: " .. package)
            if parameters ~= "" then
                print("  Args: " .. parameters)
            end
            print("")
            print("The computer will run this package on boot.")
        else
            print("Error: Failed to write startup script.")
        end
    end
}

return startupModule
